# Generated by Django 5.0.6 on 2024-06-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designoption',
            old_name='value',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='materialtype',
            old_name='value',
            new_name='rate',
        ),
    ]
